name: keep-alive-streamlit

on:
  schedule:
    - cron: "*/5 * * * *"   # a cada 5 min (em UTC)
  workflow_dispatch:        # permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Hit Streamlit app (wake & keep alive)
        run: |
          URL="https://fabicorretora.streamlit.app/?keepalive=$(date +%s)"
          echo "Pinging $URL"
          # Tenta até 5 vezes, seguindo redirecionamentos (-L) e exibindo HTTP code
          for i in {1..5}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" -A "keep-alive-bot" -L "$URL")
            echo "Attempt $i -> HTTP $code"
            # Considera sucesso qualquer 2xx ou 3xx
            if [ "$code" -ge 200 ] && [ "$code" -lt 400 ]; then
              echo "OK"
              exit 0
            fi
            sleep 10
          done
          echo "Failed to ping app."
          exit 1
