name: keep-alive-streamlit

on:
  schedule:
    - cron: '*/5 * * * *'   # a cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Ping principal
        run: |
          curl -L -I --max-time 20 --retry 2 --retry-delay 2 "https://fabicorretora.streamlit.app/" || true
      - name: Ping GET simples (mede status)
        run: |
          code=$(curl -L -s -o /dev/null -w "%{http_code}\n" --max-time 20 "https://fabicorretora.streamlit.app/" || echo "000")
          echo "::notice title=HTTP status::$code"
